### ISSUE TITLE
What is allele-A bias(+) and allele-A bias(++)

### ISSUE THREAD

**Issue by Mashuaiii** [single-cell-genetics/XClone#19]
Hi, @Rongtingting 

I'm having some problems understanding BAF output, and I want to know how to define allele-A bias(+) and allele-A bias(++).

![image](https://github.com/user-attachments/assets/12baf77e-fe31-42a6-a6d1-10b771aa14af)
![image](https://github.com/user-attachments/assets/0ea5cc88-30bf-433d-a691-7cea0a7707ee)
From the articles Figure 2a and Figure 2c, I try to understand allele bias. For example, I understand that the AAAAB result of chr1q in clone1 is allele-A bias(++), and the AAB of chr2p is allele-A bias(+). But the result of the AAB of chr2q in Figure 2C is allele-B bias(++), and the AAB of chr7 is also allele-B bias(++). Which graph has the wrong result, which makes me understand that allele bias has a problem. Now I understand that AAB is allele-A bias(+) and AAAB is allele-A bias(++). That is, if A is 2 times B, it is +, and if A is more than 2 times B, it is ++. So are AA and A + or +++?I am looking forward to hearing from you and I would appreciate it very much.

Bests,
Mashuai

**Comment by Rongtingting** [comment]
Hi @Mashuaiii ,

Actually, the allele bias states are not defined by specific copy number.
In the BAF scale (0~1), 0.5 means allele balance. if the allele shifts from 0.5, then there is allele bias.
If BAF shifts not so far from 0.5, then it is allele bias (+), e.g., BAF = 0.75.
If BAF shifts quite far from 0.5, then it is allele bias (++), e.g., BAF = 0.9.
Every dataset has its own learned BAF ranges for allele bias (+) and allele bias (++) in the XClone framework.


Bests,
Rongting

**Comment by Mashuaiii** [comment]
Thank you, I understand! 

I have another problem with the identification of normal and tumor for BAF. Sometimes the clone is not so clear, and human eyes cannot tell which is normal. May I ask if there are any quantitative indicators that can be distinguished?
![image](https://github.com/user-attachments/assets/5fc2f966-295a-4f58-a38a-5f802feffed9)
As mentioned above, could clone2 be normal? So is there a quantitative way to identify normal, such as calculating the average BAF of each clone?

Bests,
Mashuai

**Comment by Rongtingting** [comment]
Hi Mashuai,

We expect to clearly distinguish the normal part from the tumor part by visualization.
If the visualization needs clarification, maybe using BAF to get the normal part is not the first way.
Another user had tested some different datasets; not all datasets will have a clear BAF pattern if the dataset's quality is not so good.

I noticed that your dataset is GBM, and I also noticed that you have tried scONE-seq, right?
Is the dataset you tried for this issue from 10X or another tech?

A quantitative way to identify normal is good, but I still need to implement the function. Thank you for reminding me again.

Bests,
Rongting

**Comment by Mashuaiii** [comment]
Hi Rongting,

Thank you for your reply. Yeah, I test the scONE-seq and this issue is from scONE-seq. But we did filter the data a little bit.
You're doing great!

Bests,
Rongting

**Comment by Rongtingting** [comment]
Hi Mashuai,

Default "k-means" clustering is used in the exploration.
"Hierarchical" is also implemented in the [XClustering](https://github.com/single-cell-genetics/XClone/blob/d74135697520934d400f89c543d5f195077f4c62/xclone/analysis/_clustering.py#L4) function.

Bests,
Rongting
