### ISSUE TITLE
RDR preprocessing filtering out all genes

### ISSUE THREAD

**Issue by cnk113** [single-cell-genetics/XClone#9]
Hello,

I'm running into an issue with run_RDR where it filters out all genes.
It looks like the minimum gene of 3000 is not being enforced?

Thanks,
Chang

**Comment by Rongtingting** [comment]
Hi Chang,

Thank your for your feedback. Could you try the latest version?
need install from GitHub.`pip install git+https://github.com/single-cell-genetics/XClone`

**Comment by Rongtingting** [comment]
Welcome to reopen this if you still have questions on this.
